.gitignore, sonar/snap.py
This is a very extensive pull request. It is much longer than it should be, but I hope it is ok, since we are still in the beginning, when much is to be tested. A short changelog of the more important changes. The changelog is also in the commit message of the main commit.
Changed top to ps. Following reasons:
- ps is independent on locale (top turns e.g. CPU 2.3% to 2,3% depending on locale)
- ps does not produce the header that has to be shaved of
- ps is (arguably) more adaptable/configurable
Rewrote extract_processes and its test accordingly, so it works with the new ps solution.
Renamed get_slurm_project to get_slurm_projects (with s) as it will get all user-to-project mappings on the node.
Implemented get_slurm_projects. It will only get the active users (and their projects) on the …
=> Refactured snap.py

setup.py, sonar/cli.py, sonar/map.py, sonar/snap.py
Replace click with argparse to enable calling `sonar <subcommand> --arguments` instead of `sonar-<subcommand> --arguments` as before.
=> Replace click with argparse to use a single major command for everything

src/ps.rs
This adds GPU monitoring for nvidia cards, as well as zombie hunting functionality for the same.  It uses the nvidia-smi tool for (relative) simplicity, but needs to invoke it twice and the output is documented as not being stable, so it may be better to consider going directly to the monitoring libraries.  Also, the nvidia code has been folded into ps.rs for now but we could discuss whether it's worth disentangling.
=> nvidia monitoring

src/amd.rs, src/main.rs, src/nvidia.rs, src/process.rs, src/ps.rs
This parses the output of rocm-smi to generate GPU usage data for AMD, as for NVIDIA.  It's a bit of a hack but is reliable in my testing - I have a machine with two NVIDIA cards, and some test code that uses both of them.
I think that our nervousness about running nvidia-smi (see #44) is going to be even more acute for rocm-smi.
~~(The base rev here is not the tip of my work queue but the underlying main refactoring of ps.rs, #45, a little rebasing work will be required to land this if all the other patches land first.)~~
=> Amd gpu support

README.md, src/util.rs
- do not write sub-second precision
- write data in local time, but with timezone information
=> update timestamp function; closes #34, closes #64

src/main.rs, src/ps.rs
later we can use something from
https://rust-lang-nursery.github.io/rust-cookbook/development_tools/debugging/log.html
=> log_cmderror is only used in one file, moving definition there

Cargo.lock, Cargo.toml, src/amd.rs, src/command.rs, src/main.rs, src/nvidia.rs, src/ps.rs
Basically:
- propagate errors from lower layers (haven't done anything about the slurm component yet) as meaningful strings
- carry the failed command and its output (if any) with the CmdError
- use the standard logger to log these errors
This change pulls in a fair amount of code, I think chiefly through the env_logger library used to initialize logging.
For my purposes, this logging (to stderr) is roughly what I want, since cron captures the output and emails it to me.  But it may get further tweaking down the line.
=> Better error reporting.  Fixes #52

src/process.rs, src/ps.rs
Extract the `cputimes` field from ps and add it onto the end of the output, after the GPU fields.  Clients that can parse optional fields (such as the gpu fields) should not be disturbed by this.
=> Add cputimes.  Fixes #68

Cargo.lock, Cargo.toml, README.md, src/amd.rs, src/command.rs, src/nvidia.rs, src/ps.rs, src/util.rs
Summary:
- changes output format (which is explained in README.md)
- bumps version to 0.7.0
Please see the change in README.md for how the columns are defined. @lars-t-hansen can you please browse through this change carefully?
I am unsure about the `gpus` part.
- If a process would use GPUs 1, 3, and 7: `"gpus={1, 3, 7}"`
- If a process would use no or unknown GPUs: `gpus={}`
Do we want to distinguish no GPUs and unknown GPUs? If yes, how?
=> make output fields self-identifying; closes #41

README.md, src/main.rs, src/process.rs, src/ps.rs, src/util.rs
As discussed on #78, the use of user name and command name to distinguish process records and the attempted merging of process records that have the same user name and command name are vestiges of an older design.  This patch removes all of that and does the following:
- the pid is the unique key for a record internally
- information from multiple sources for the same pid are merged into the unique record for the pid
- the record is tagged with its job id but the job id is not a distinguishing characteristic of anything, internally
- as a result, there may be multiple records for the same job in the output, but this was always the case; now it is documented
- the intermediate "rolling up" of ps and gpu records with the same user, pid, and command is not necessary and has been removed
- it …
=> Revamp ps.  Fixes #78

.gitignore, src/amd.rs, src/batchless.rs, src/jobs.rs, src/main.rs, src/nvidia.rs, src/process.rs, src/ps.rs, src/slurm.rs
Major points:
- The filtering that we used to run directly after the ps subprocess has been removed
- The previous patch already moved filtering to the printing code in ps.rs, here we just expand on that
- We add a number of command line options to specify how jobs are filtered (more are possible but I figure we'll follow up with individual patches, driven by need)
- Existing command line options are cleaned up to create a coherent set and the filtering logic is itself tidied up
- We extract uid along with the user to more easily filter out system processes, this is fairly disruptive but mechanical
- Some minor drive-by cleanup
-
=> Even better filtering.  Fix #73

src/amd.rs, src/main.rs, src/nvidia.rs, src/process.rs
This seems to take care of the timeout problems I was seeing on our busiest systems.
=> Make timeout 5s, and share it.  Fix #92.

src/main.rs, src/ps.rs
Draft, pending resolution to the discussion in #107, but ready to go if this is how we decide to do it.
This prints a synthetic heartbeat record from `sonar ps` if nothing else has been printed, and does not need a command line switch to do so - it always does it.  Easy to add a switch if we need it.
=> Fix #107: Always print at least one record

src/main.rs, src/process.rs, src/procfs.rs, src/procfsapi.rs, src/ps.rs
This is the first step.  procfs is virtualized completely so that it's possible to inject data into it (easily, too).
=> For #94 - virtualize procfs, add tests

Cargo.lock, Cargo.toml, README.md, src/process.rs, src/procfs.rs, src/procfsapi.rs, src/ps.rs
Four patches in this queue but only the last one (Compute resident memory) should have any drama, the others are cleanup that became necessary/desirable.  Probably worth mentioning that the "Refactor memtotal" patch adds an output field for RAM installed (to complement the core count field) and increases the version number to 0.8.0.
For resident memory, I currently go for the RssAnon fields of /proc/pid/status (and the drs field of the ps output, which is somewhat closely related), and the output field is called "rssanon".  Should we choose to print more fields or other fields we can then name them precisely.  This is better than having a definition that shifts or a name that is easy to misinterpret.
=> Fix #126 - report resident memory

README.md, src/ps.rs
There didn't seem to be any good reason to make things more complicated than not printing zero-valued fields.
=> Fix #74 - Don't print fields with default values

Cargo.lock, Cargo.toml, src/amd.rs, src/gpu.rs, src/main.rs, src/nvidia.rs, src/procfs.rs, src/sysinfo.rs
This seems to be feature complete and working, I just need to make a final pass before asking for review.
=> Fix #142 - implement sysinfo

Cargo.lock, Cargo.toml
The wait-timeout library is no longer used by sonar, it's a dead dependency in Cargo.toml.
=> For #152 - remove wait-timeout dependency

Cargo.lock, Cargo.toml, src/hostname.rs, src/main.rs, src/ps.rs, src/sysinfo.rs
Not the biggest thing, but the code is simple, MIT-licensed, and depends only on libc, so let's just incorporate the one function we need.  In this respect it is like the `users` library we also incorporated previously.
=> For #152 - Remove hostname dependency

Cargo.lock, Cargo.toml, src/main.rs, src/time.rs, src/util.rs
Libc has everything we need, so just get rid of chrono altogether.  With all the patches applied we are now down to four explicit dependencies and 9 in total (and code size is reduced by approximately 75%).
=> For #152 - Remove chrono dependency

Cargo.toml
Disable features we don't need (we only need the "set a flag atomically" feature), until we can figure out if it's possible to get rid of this dependency.
=> For #152 - Limit signal-hook features

Cargo.lock, Cargo.toml, src/sysinfo.rs, src/util.rs, tests/sysinfo-syntax.sh
This removes serde_json and the direct dependency on serde (though serde is still included indirectly via csv).
=> For #152 - Remove serde_json dependency

Cargo.lock, Cargo.toml, src/log.rs, src/main.rs, src/ps.rs, src/sysinfo.rs
Still thinking about this, but currently sonar is not using any of the functionality of env_logger or log: it just writes the error message on stderr.  And the conclusion in #52 was that this is Just Fine.  Ergo the logging functions, which are ergonomically right, need only be thin wrappers around eprintln.
This gets rid of lots of dependencies since env_logger pulls in regexp and its dependencies, among other things.  Binary size drops by 50%.
=> For #152 - Remove env_logger and log dependencies

src/amd.rs, src/command.rs, src/nvidia.rs
Improves efficiency, makes accidents harder, and sets us up for getting rid of the subprocess library.
=> Fix #88 - spawn subprograms directly, not via shell

.zenodo.json, Cargo.lock, Cargo.toml, README.md, src/batchless.rs, src/jobs.rs, src/main.rs, src/procfs.rs, src/ps.rs, src/slurm.rs, tests/.gitignore, tests/Makefile, tests/rollup.c, tests/rollup.sh, tests/rollup2.c, tests/rollup2.sh, tests/rollupchild.c
This is an attempt to put us on firm footing for doing proper accounting of batchless nested jobs (which are a thing, see bug).  In short:
- make the process group the job id
- make rollups more discerning (which would be the right thing even if it were not necessary for this fix)
- emit parent pid
- make --rollup incompatible with --batchless because the latter leads to data loss we can't cope with
=> Fix #89 - revamp job id, rollup, emit ppid

.zenodo.json, Cargo.lock, Cargo.toml, README.md, src/main.rs, src/procfs.rs, src/ps.rs, tests/load.sh, tests/run_tests.sh
Currently a WIP, decoding /proc/stat and outlining various representation strategies for the data to make them compact.  There are endless possibilities, but a base-45 variable-length delta-from-minimum encoding with separators represented as distinguished leading digits is probably about as compact as more standard encodings (eg uleb64+base64), and simpler than the latter.
=> Fix #178 - extract numa info

src/amd.rs, src/hostname.rs, src/nvidia.rs, src/procfs.rs, src/procfsapi.rs, src/ps.rs, src/sysinfo.rs, src/time.rs
In test cases, use `expect` instead of `unwrap`, with a string that clearly marks it as a test case.
In most other cases, use `expect` if there was an existing check on the path (typically `is_some`) and otherwise rewrite the code using `match`.
In a couple of cases, the `expect` checks a complex precondition and now properly documents that.
There are two cases of `panic` that have been commented but left alone.
=> Fix #168 - get rid of all cases of unwrap()

src/command.rs
Baby steps, but at least something.
=> Fix #96 - add more information to errors in subprocess execution

src/amd.rs, src/gpu.rs, src/nvidia.rs, src/ps.rs, src/sysinfo.rs, src/testdata/nvidia-smi-output.txt, tests/gpuinfo.sh, tests/run_tests.sh
NOTE, this sits on top of #203 and needs to be rebased once that lands!
=> #201 - Per-gpu load data

Cargo.lock, src/amd.rs
This patch is a bit bigger than it needs to be: it reorganizes the file a little, moving test cases to the end.  Interleaving code and test cases was an experiment (keep tests close to the code) that was a failure.
=> For #209 - deal with newer rocm-smi output (release_0_12)

src/amd.rs
Uplift from release_0_12 (see #213).  This is a little more disciplined, it doesn't move so much code around.
=> For #209 - Parse new rocm-smi output (main)

tests/amd-gpu.sh, tests/nvidia-gpu.sh, tests/run_tests.sh
These tests are run as part of the normal test cycle but will only do something on nodes that have the AMD/NVIDIA cards installed.  Mostly, therefore, actual testing will happen on nodes we control and not on the github runner.
=> No bug - very basic GPU logic test cases (release_0_12)

src/amd.rs
No uplift for this, it is specific to this branch.
=> Fix #209 - Do not crash on parse failure (release_0_12)

src/ps.rs, tests/no-gpu.sh, tests/run_tests.sh
Move the setting of the error flag into an error case, add a test case.
=> Fix #229 - gpu probe regression

.github/workflows/test-minimal.yml, .github/workflows/test.yml, README.md
This is not ready yet - I am debugging this ...
=> Document minimum required versions and test it

src/main.rs, src/output.rs, src/ps.rs, src/slurmjobs.rs, src/sysinfo.rs, tests/ps-syntax.sh, tests/run_tests.sh, tests/slurm-syntax.sh, tests/sysinfo-syntax.sh
This allows all operations to print csv or json (and in the future, eg a binary format) by abstracting the output logic.  Generally this is a nice improvement since it separates the output logic completely from the rest of the program logic.
TODO here:
=> Fix #228 - better output logic

src/amd_smi.rs, src/nvidia_nvml.rs
Seems gpu min max power_limits had been accidentally swapped
=> gpu: fix extraction of min / max power limit

.gitignore, Cargo.toml, README.md, doc/HOWTO-DAEMON.md, src/cluster.rs, src/daemon.rs, src/datasink.rs, src/main.rs, src/ps.rs, src/realsystem.rs, src/slurmjobs.rs, src/sysinfo.rs, src/testdata/daemon-stdio-config.txt, src/time.rs, tests/features.sh, util/ingest-files/.gitignore
This is the base patch from #280, which is clean enough to land by itself.
This is a big patch, but there are two main changes here:
- the introduction of the "daemon" code and some supporting code, all of which is dormant unless actively used
- a rewrite of the sacct interface to break apart data extraction and formatting, this was overdue anyway and will be needed for subsequent work
This patch only has exfiltration to stdout / control messages from stdin, but has a simple API so that other exfiltration methods can be added, this has been vetted with a Kafka interface on the other queue.
=> For #147 - Daemon with stdio exfiltration/control

doc/HOWTO-DAEMON.md, src/daemon.rs, src/datasink.rs, tests/daemon-test.ini, tests/daemon.sh, tests/run_tests.sh
This does several things:
- add an optional topic prefix, see #284 for design notes, and document it
- makes the stdio sink require a topic on control messages read from stdin
- make the stdio sink a little more prominent in documentation
- add a regression test case for the daemon code using the stdio sink, sadly this was forgotten previously
=> Fix #284 - optional topic prefix

.github/workflows/test-go-format.yml, .github/workflows/test-rust-format.yml, src/datasink.rs, src/slurmjobs.rs, src/sysinfo.rs, tests/go-format.sh, tests/rust-format.sh, util/formats/newfmt/types.go
The checks for proper format are both fast (given how tiny the repo is) so I've broken them out as separate workflows.  Also included are some reformats, of course, since otherwise this PR would not pass the tests...  The new tests have to be run manually from the tests directory, they are not integrated into run_tests.sh, see the bug for discussion.
=> Fix #274 - check Rust and Go code formatting

doc/NEW-FORMAT.md, src/json_tags.rs, src/linux/mocksystem.rs, src/linux/procfs.rs, src/linux/procfs_test.rs, src/linux/procfsapi.rs, src/linux/system.rs, src/ps.rs, src/ps_newfmt.rs, src/systemapi.rs, util/formats/newfmt/types.go
@2maz note this adds a `num_threads` fields to the per-process sample object.
=> For #242 - simplify some old code

LICENSE, util/formats/LICENSE, util/formats/newfmt/decode_cluster.go, util/formats/newfmt/decode_jobs.go, util/formats/newfmt/decode_samples.go, util/formats/newfmt/decode_sysinfo.go, util/formats/newfmt/to_oldfmt.go, util/formats/newfmt/types.go, util/formats/newfmt_test.go, util/formats/oldfmt/decode_samples.go, util/formats/oldfmt/decode_slurm.go, util/formats/oldfmt/decode_sysinfo.go, util/formats/oldfmt/types.go, util/formats/oldfmt_test.go, util/formats/testing.go
Relicense code in util/formats (only) under the MIT license and claim the copyright of that code for NAIC.
I would not want this to be seen as some kind of fait accompli so by all means lets discuss, but I hope this is a sensible compromise.
=> Fix #293 - Relicense util/formats

src/cluster.rs, src/linux/mocksystem.rs, src/linux/system.rs, src/main.rs, src/systemapi.rs
There's nothing really slurm-specific about the 'cluster' command so hide the dependency a little.
=> No bug: Cleanup: decouple 'cluster' from slurm
